// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TollRoad.Models;

public partial class Employee
{
    public int Id { get; set; }

    public string Surname { get; set; }

    public string Name { get; set; }

    public string Patronymic { get; set; }

    public string PhoneNumber { get; set; }

    public byte[] Photo { get; set; }

    public int? IdCheckpoint { get; set; }

    public int IdRole { get; set; }

    public int IdGender { get; set; }

    public string Login { get; set; }

    public string Password { get; set; }

    public virtual Checkpoint IdCheckpointNavigation { get; set; }

    public virtual Gender IdGenderNavigation { get; set; }

    public virtual Role IdRoleNavigation { get; set; }

    public override string ToString()
    {
        return Surname + " " + Name + " " + Patronymic +
                PhoneNumber + " " + IdCheckpointNavigation + " " + Login + " " + Password + " "
                + IdRoleNavigation.RoleName + " " + IdGenderNavigation.GenderName;
    }
}