// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TollRoad.Models;

public partial class Gender
{
    public int Id { get; set; }

    public string GenderName { get; set; }

    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();

    public override string ToString()
    {
        return GenderName;
    }
}