// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TollRoad.Models;

public partial class PhotoOfCheckpoint
{
    public int IdCheckpoint { get; set; }

    public int NumberOfPhoto { get; set; }

    public byte[] Photo { get; set; }

    public virtual Checkpoint IdCheckpointNavigation { get; set; }
}