// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TollRoad.Models;

public partial class StatusesOfTrip
{
    public int Id { get; set; }

    public string StatusName { get; set; }

    public virtual ICollection<Trip> Trips { get; set; } = new List<Trip>();

    public override string ToString()
    {
        return StatusName;
    }
}