// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TollRoad.Models;

public partial class Vehicle
{
    public int Id { get; set; }

    public string StateNumber { get; set; }

    public int WidthInMm { get; set; }

    public int HeightInMm { get; set; }

    public int WeightInKg { get; set; }

    public int CategoryOfVehicle { get; set; }

    public virtual VehicleCategory CategoryOfVehicleNavigation { get; set; }

    public virtual ICollection<Trip> Trips { get; set; } = new List<Trip>();

    public override string ToString()
    {
        return StateNumber + " " + WidthInMm + " " + HeightInMm + " " + WeightInKg + " " + CategoryOfVehicleNavigation.CategoryName;
    }
}